[package]
name = "psce"
version = "0.1.0"
edition = "2021"
default-run = "interactive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.1.0"
strum = { version = "0.26.2", features = ["derive"] }
