[package]
name = "psce_movegen_generated"
version = "0.0.0"
edition = "2024"

[dependencies]

[build-dependencies]
psce_movegen_generator = { path = "../generator" }
psce_core = { path = "../../core" }
